// <auto-generated />
using HotelApi.DbManager;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace HotelApi.Migrations
{
    [DbContext(typeof(HotelContext))]
    partial class HotelContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HotelApi.Hotel", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("HotelRegionId");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<int>("RoomsAvaiable");

                    b.HasKey("Id");

                    b.HasIndex("HotelRegionId");

                    b.ToTable("Hotel");
                });

            modelBuilder.Entity("HotelApi.HotelRegion", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("HotelRegions");
                });

            modelBuilder.Entity("HotelApi.Hotel", b =>
                {
                    b.HasOne("HotelApi.HotelRegion", "Region")
                        .WithMany("Hotels")
                        .HasForeignKey("HotelRegionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
